services:
  webserver:
    build: .
    restart: always
    ports:
      - "80:80"
    networks:
      - rekt0_bridge
    depends_on:
      - database
  
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      MYSQL_DATABASE: bookstore_db
      MYSQL_USER: rekt0zarius
      MYSQL_PASSWORD: ${DB_PASS}
    networks:
      - rekt0_bridge

networks:
  rekt0_bridge:
    driver: bridge